# Very simple docker-compose file to run the app on http://localhost:3000 (or http://127.0.0.1:3000).
#
# For more examples, such runnin big-AGI alongside a web browsing service, see the `docs/docker` folder.

version: '3.9'

services:
  big-agi:
    container_name: big-agi
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: [ "next", "start", "-p", "3000" ]
    networks:
      - ai
      
  browserless:
    image: browserless/chrome:latest
    env_file:
      - .env
    ports:
      - "9222:3000"  # Map host's port 9222 to container's port 3000
    environment:
      - MAX_CONCURRENT_SESSIONS=10
    networks:
      - ai

  edge-tts:
    image: herberthe0229/edge-tts-server
    ports:
      - "8089:8088"
    networks:
      - ai

networks:
  ai:
    external: true
      